version: "3.9"
services:
  db:
    image: postgis/postgis:14-master
    user: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: plexjob
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db
